version: "2"
services:
  uwsgi:
    build: ./app
    volumes:
      - ./app:/var/www:z
      - /etc/localtime:/usr/share/zoneinfo/Japan:ro
    ports:
      - "3031:3031"
    environment:
      TZ: "Asia/Tokyo"

  nginx:
    build: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:z
      - /etc/localtime:/usr/share/zoneinfo/Japan:ro
    links:
      - uwsgi
    ports:
      - "5000:80"
    environment:
      TZ: "Asia/Tokyo"
